/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VirusSniper;

import javax.swing.*;
import java.awt.Dimension;

/**
 *
 * @author Andrew
 */
public class RegistryFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegistryFrame
     */
    public RegistryFrame() {
        msg = new JFrame();// Used as the JOptionPane Frame
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        checkRunKeyButton = new javax.swing.JButton();
        checkRunOnceKeyButton = new javax.swing.JButton();
        checkControlPanelAccessibilityKeyButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        MainMenuPanel = new javax.swing.JPanel();
        MainMenuLbl = new javax.swing.JLabel();

        setTitle("Registry Scan");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(0, 0));
        setName("RegistryFrame"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/Virus Sniper.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        checkRunKeyButton.setText("Check Run key");
        checkRunKeyButton.setToolTipText("Check HCLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run");
        checkRunKeyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRunKeyButtonActionPerformed(evt);
            }
        });

        checkRunOnceKeyButton.setText("Check RunOnce key");
        checkRunOnceKeyButton.setToolTipText("Check HKLM\\Software\\Mircosoft\\Windows\\CurrentVersion\\RunOnce Key");
        checkRunOnceKeyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRunOnceKeyButtonActionPerformed(evt);
            }
        });

        checkControlPanelAccessibilityKeyButton.setText("Check Accessibility key");
        checkControlPanelAccessibilityKeyButton.setToolTipText("Check HKCU\\Control Panel\\Accessibility Key");
        checkControlPanelAccessibilityKeyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkControlPanelAccessibilityKeyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkRunKeyButton)
                    .addComponent(checkRunOnceKeyButton)
                    .addComponent(checkControlPanelAccessibilityKeyButton))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkRunKeyButton)
                .addGap(18, 18, 18)
                .addComponent(checkRunOnceKeyButton)
                .addGap(18, 18, 18)
                .addComponent(checkControlPanelAccessibilityKeyButton)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));

        MainMenuPanel.setBackground(new java.awt.Color(0, 102, 153));
        MainMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainMenuPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MainMenuPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MainMenuPanelMouseExited(evt);
            }
        });

        MainMenuLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MainMenuLbl.setForeground(new java.awt.Color(255, 255, 255));
        MainMenuLbl.setText("Main Menu");

        javax.swing.GroupLayout MainMenuPanelLayout = new javax.swing.GroupLayout(MainMenuPanel);
        MainMenuPanel.setLayout(MainMenuPanelLayout);
        MainMenuPanelLayout.setHorizontalGroup(
            MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(MainMenuLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        MainMenuPanelLayout.setVerticalGroup(
            MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenuLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkRunKeyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRunKeyButtonActionPerformed
        // Calls the Registry class to read the provided location in the registry
        Registry reg = new Registry();
        // Call to the readRegistry method with the provided location String
        String result = reg.readRegistry("HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run");
        JTextArea text = new JTextArea(result);
        JScrollPane scroll = new JScrollPane(text);
        text.setLineWrap(true);
        text.setWrapStyleWord(true);
        scroll.setPreferredSize(new Dimension(650,200));
        JOptionPane.showMessageDialog(msg,scroll,
                "Registry result", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_checkRunKeyButtonActionPerformed

    private void checkRunOnceKeyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRunOnceKeyButtonActionPerformed
        // Calls the Registry class to read the provided location in the registry
        Registry reg = new Registry();
        // Call to the readRegistry method with the provided location String
        String result = reg.readRegistry("HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\RunOnce");
        JTextArea text = new JTextArea(result);
        JScrollPane scroll = new JScrollPane(text);
        text.setLineWrap(true);
        text.setWrapStyleWord(true);
        scroll.setPreferredSize(new Dimension(650,200));
        JOptionPane.showMessageDialog(msg,scroll,
                "Registry result", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_checkRunOnceKeyButtonActionPerformed

    private void checkControlPanelAccessibilityKeyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkControlPanelAccessibilityKeyButtonActionPerformed
        // Calls the Registry class to read the provided location in the registry
        Registry reg = new Registry();
        // Call to the readRegistry method with the provided location String
        String result = reg.readRegistry("\"HKCU\\Control Panel\\Accessibility\" /s");
        JTextArea text = new JTextArea(result);
        JScrollPane scroll = new JScrollPane(text);
        text.setLineWrap(true);
        text.setWrapStyleWord(true);
        scroll.setPreferredSize(new Dimension(650,200));
        JOptionPane.showMessageDialog(msg,scroll,
                "Registry result", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_checkControlPanelAccessibilityKeyButtonActionPerformed

    private void MainMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainMenuPanelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_MainMenuPanelMouseClicked

    private void MainMenuPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainMenuPanelMouseEntered
        // TODO add your handling code here:
        JPanel parent = (JPanel) evt.getSource();
        parent.setBackground(new java.awt.Color(0, 0, 102));
    }//GEN-LAST:event_MainMenuPanelMouseEntered

    private void MainMenuPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainMenuPanelMouseExited
        // TODO add your handling code here:
        JPanel parent = (JPanel) evt.getSource();
        parent.setBackground(new java.awt.Color(0, 102, 153));
    }//GEN-LAST:event_MainMenuPanelMouseExited


    private JFrame msg; //Used for the JOption Panel pop up message after you scan an entry
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainMenuLbl;
    private javax.swing.JPanel MainMenuPanel;
    private javax.swing.JButton checkControlPanelAccessibilityKeyButton;
    private javax.swing.JButton checkRunKeyButton;
    private javax.swing.JButton checkRunOnceKeyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}