/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VirusSniper;

import java.awt.*;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author craig
 */
public class VirusSniperGUI extends javax.swing.JFrame {

    public static VirusSniperGUI main_gui;
    String image_path = "images/";
    Popup p;

    /**
     * Creates new form VirusSniperGUI
     */
    public VirusSniperGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        reportListPanel = new JPanel();
        reportListPanel.setLayout(new BoxLayout(reportListPanel, BoxLayout.Y_AXIS));

        bg = new javax.swing.JPanel();
        scanTitlePanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        scanPanel = new javax.swing.JPanel();
        scanIcon = new javax.swing.JLabel();
        scanLabel = new javax.swing.JLabel();
        reportsPanel = new javax.swing.JPanel();
        reportIcon = new javax.swing.JLabel();
        reportsLabel = new javax.swing.JLabel();
        quarantinedFilesPanel = new javax.swing.JPanel();
        quarantineIcon = new javax.swing.JLabel();
        quarantineLabel = new javax.swing.JLabel();
        settingsPanel = new javax.swing.JPanel();
        settingsIcon = new javax.swing.JLabel();
        settingsLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        displayScansPanel = new javax.swing.JPanel();
        virusIcon = new javax.swing.JLabel();
        fileScanButton = new javax.swing.JButton();
        suspiciousIcon = new javax.swing.JLabel();
        suspiciousActivityButton = new javax.swing.JButton();
        venomIcon = new javax.swing.JLabel();
        venomScanButton = new javax.swing.JButton();
        registryIcon = new javax.swing.JLabel();
        registryButton = new javax.swing.JButton();
        displayReportsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane(reportListPanel);
        reportsPanelLabel = new javax.swing.JLabel();
        displayQuarantinedPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        quarantinedTable = new javax.swing.JTable();
        displaySettingsPanel = new javax.swing.JPanel();
        scanTimeLabel = new javax.swing.JLabel();
        scanTimeTF = new javax.swing.JTextField();
        scanTimeCB = new javax.swing.JComboBox<>();
        clearReportsLabel = new javax.swing.JLabel();
        clearReportsButton = new javax.swing.JButton();
        shredQuarantinedLabel = new javax.swing.JLabel();
        shredQuarantinedButton = new javax.swing.JButton();
        scanTimeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Virus Sniper Anti-Virus");
        //setAlwaysOnTop(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));

        scanTitlePanel.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout scanTitlePanelLayout = new javax.swing.GroupLayout(scanTitlePanel);
        scanTitlePanel.setLayout(scanTitlePanelLayout);
        scanTitlePanelLayout.setHorizontalGroup(
                scanTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        scanTitlePanelLayout.setVerticalGroup(
                scanTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 111, Short.MAX_VALUE)
        );

        sidePanel.setBackground(new java.awt.Color(0, 102, 153));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource(image_path + "Virus Sniper.png"))); // NOI18N
        logo.setText("jLabel1");

        scanPanel.setBackground(new java.awt.Color(0, 102, 153));
        scanPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scanPanelMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                scanPanelMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                scanPanelMouseExited(evt);
            }
        });

        scanIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scanIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource(image_path + "magnifying-glass.png"))); // NOI18N

        scanLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        scanLabel.setForeground(new java.awt.Color(255, 255, 255));
        scanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scanLabel.setText("Scans");

        javax.swing.GroupLayout scanPanelLayout = new javax.swing.GroupLayout(scanPanel);
        scanPanel.setLayout(scanPanelLayout);
        scanPanelLayout.setHorizontalGroup(
                scanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(scanPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(scanIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(scanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        scanPanelLayout.setVerticalGroup(
                scanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(scanPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(scanIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scanPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(scanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
        );

        reportsPanel.setBackground(new java.awt.Color(0, 102, 153));
        reportsPanel.setToolTipText("");
        reportsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsPanelMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportsPanelMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportsPanelMouseExited(evt);
            }
        });

        reportIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource(image_path + "report.png"))); // NOI18N

        reportsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reportsLabel.setForeground(new java.awt.Color(255, 255, 255));
        reportsLabel.setText("Reports");

        javax.swing.GroupLayout reportsPanelLayout = new javax.swing.GroupLayout(reportsPanel);
        reportsPanel.setLayout(reportsPanelLayout);
        reportsPanelLayout.setHorizontalGroup(
                reportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(reportsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(reportIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(reportsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        reportsPanelLayout.setVerticalGroup(
                reportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(reportsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(reportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(reportsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(reportIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                                .addContainerGap())
        );

        quarantinedFilesPanel.setBackground(new java.awt.Color(0, 102, 153));
        quarantinedFilesPanel.setToolTipText("");
        quarantinedFilesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    quarantinedFilesPanelMouseClicked(evt);
                } catch (IOException ex) {
                    Logger.getLogger(VirusSniperGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NoSuchAlgorithmException ex) {
                    Logger.getLogger(VirusSniperGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                quarantinedFilesPanelMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                quarantinedFilesPanelMouseExited(evt);
            }
        });

        quarantineIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quarantineIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource(image_path + "quarantined.png"))); // NOI18N

        quarantineLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        quarantineLabel.setForeground(new java.awt.Color(255, 255, 255));
        quarantineLabel.setText("Quarantined Files");

        javax.swing.GroupLayout quarantinedFilesPanelLayout = new javax.swing.GroupLayout(quarantinedFilesPanel);
        quarantinedFilesPanel.setLayout(quarantinedFilesPanelLayout);
        quarantinedFilesPanelLayout.setHorizontalGroup(
                quarantinedFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(quarantinedFilesPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(quarantineIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(quarantineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(38, Short.MAX_VALUE))
        );
        quarantinedFilesPanelLayout.setVerticalGroup(
                quarantinedFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(quarantinedFilesPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(quarantinedFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(quarantineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(quarantineIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                                .addContainerGap())
        );

        settingsPanel.setBackground(new java.awt.Color(0, 102, 153));
        settingsPanel.setToolTipText("");
        settingsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsPanelMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsPanelMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsPanelMouseExited(evt);
            }
        });

        settingsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource(image_path + "gear.png"))); // NOI18N

        settingsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        settingsLabel.setForeground(new java.awt.Color(255, 255, 255));
        settingsLabel.setText("Settings");

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
                settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(settingsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(settingsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(settingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(54, Short.MAX_VALUE))
        );
        settingsPanelLayout.setVerticalGroup(
                settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(settingsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(settingsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(settingsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                                .addContainerGap())
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
                sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(sidePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(quarantinedFilesPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(reportsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(scanPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(settingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
                sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sidePanelLayout.createSequentialGroup()
                                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(scanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(reportsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(quarantinedFilesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(settingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        displayScansPanel.setBackground(new java.awt.Color(255, 255, 255));
        displayScansPanel.setToolTipText("");

        virusIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource(image_path + "virus.png"))); // NOI18N

        fileScanButton.setBackground(new java.awt.Color(0, 102, 153));
        fileScanButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        fileScanButton.setForeground(new java.awt.Color(255, 255, 255));
        fileScanButton.setText("File Scan");
        fileScanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileScanButtonActionPerformed(evt);
            }
        });

        suspiciousIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        suspiciousIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource(image_path + "hacking.png"))); // NOI18N

        suspiciousActivityButton.setBackground(new java.awt.Color(0, 102, 153));
        suspiciousActivityButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        suspiciousActivityButton.setForeground(new java.awt.Color(255, 255, 255));
        suspiciousActivityButton.setText("Suspicious Activity");
        suspiciousActivityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suspiciousActivityButtonActionPerformed(evt);
            }
        });

        venomIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource(image_path + "laptop-coding.png"))); // NOI18N

        venomScanButton.setBackground(new java.awt.Color(0, 102, 153));
        venomScanButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        venomScanButton.setForeground(new java.awt.Color(255, 255, 255));
        venomScanButton.setText("MSF Venom Scan");
        venomScanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                venomScanButtonMouseClicked(evt);
            }
        });

        registryIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registryIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource(image_path + "tree-structure.png"))); // NOI18N

        registryButton.setBackground(new java.awt.Color(0, 102, 153));
        registryButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        registryButton.setForeground(new java.awt.Color(255, 255, 255));
        registryButton.setText("Registry Scan");
        registryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registryButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout displayScansPanelLayout = new javax.swing.GroupLayout(displayScansPanel);
        displayScansPanel.setLayout(displayScansPanelLayout);
        displayScansPanelLayout.setHorizontalGroup(
                displayScansPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(displayScansPanelLayout.createSequentialGroup()
                                .addGroup(displayScansPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(displayScansPanelLayout.createSequentialGroup()
                                                .addGap(99, 99, 99)
                                                .addGroup(displayScansPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(displayScansPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(virusIcon)
                                                                .addComponent(fileScanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(venomIcon)))
                                        .addGroup(displayScansPanelLayout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(venomScanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(92, 92, 92)
                                .addGroup(displayScansPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(suspiciousIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(suspiciousActivityButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(registryIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(registryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(141, Short.MAX_VALUE))
        );
        displayScansPanelLayout.setVerticalGroup(
                displayScansPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(displayScansPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(displayScansPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(displayScansPanelLayout.createSequentialGroup()
                                                .addComponent(virusIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(fileScanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(displayScansPanelLayout.createSequentialGroup()
                                                .addComponent(suspiciousIcon)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(suspiciousActivityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41)
                                .addGroup(displayScansPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(registryIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(venomIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(displayScansPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(venomScanButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                        .addComponent(registryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(63, Short.MAX_VALUE))
        );

        mainPanel.add(displayScansPanel, "scanCard");

        displayReportsPanel.setBackground(new java.awt.Color(255, 255, 255));

        reportsPanelLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        reportsPanelLabel.setForeground(new java.awt.Color(0, 102, 153));
        reportsPanelLabel.setText("Select a Report");

        javax.swing.GroupLayout displayReportsPanelLayout = new javax.swing.GroupLayout(displayReportsPanel);
        displayReportsPanel.setLayout(displayReportsPanelLayout);
        displayReportsPanelLayout.setHorizontalGroup(
                displayReportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(displayReportsPanelLayout.createSequentialGroup()
                                .addComponent(reportsPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 467, Short.MAX_VALUE))
                        .addGroup(displayReportsPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addContainerGap())
        );
        displayReportsPanelLayout.setVerticalGroup(
                displayReportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayReportsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(reportsPanelLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(displayReportsPanel, "reportsCard");

        displayQuarantinedPanel.setBackground(new java.awt.Color(255, 255, 255));

        quarantinedTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        quarantinedTable.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        quarantinedTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Filename", "Quarantine Date", "MD5 Hash", "Signature"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        jScrollPane2.setViewportView(quarantinedTable);

        javax.swing.GroupLayout displayQuarantinedPanelLayout = new javax.swing.GroupLayout(displayQuarantinedPanel);
        displayQuarantinedPanel.setLayout(displayQuarantinedPanelLayout);
        displayQuarantinedPanelLayout.setHorizontalGroup(
                displayQuarantinedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(displayQuarantinedPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                                .addContainerGap())
        );
        displayQuarantinedPanelLayout.setVerticalGroup(
                displayQuarantinedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        mainPanel.add(displayQuarantinedPanel, "quarantinedCard");

        displaySettingsPanel.setBackground(new java.awt.Color(255, 255, 255));

        scanTimeLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        scanTimeLabel.setForeground(new java.awt.Color(0, 102, 153));
        scanTimeLabel.setText("Scan Time Length");

        scanTimeTF.setBackground(new java.awt.Color(240, 240, 240));
        scanTimeTF.setText("7");

        scanTimeCB.setBackground(new java.awt.Color(0, 102, 153));
        scanTimeCB.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        scanTimeCB.setForeground(new java.awt.Color(255, 255, 255));
        scanTimeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Days", "Months", "Years"}));

        clearReportsLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        clearReportsLabel.setForeground(new java.awt.Color(0, 102, 153));
        clearReportsLabel.setText("Delete All Reports");

        clearReportsButton.setBackground(new java.awt.Color(0, 102, 153));
        clearReportsButton.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        clearReportsButton.setForeground(new java.awt.Color(255, 255, 255));
        clearReportsButton.setText("Clear Reports");
        clearReportsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearReportsButtonMouseClicked(evt);
            }
        });

        shredQuarantinedLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        shredQuarantinedLabel.setForeground(new java.awt.Color(0, 102, 153));
        shredQuarantinedLabel.setText("Shred Quarantined Files");

        shredQuarantinedButton.setBackground(new java.awt.Color(0, 102, 153));
        shredQuarantinedButton.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        shredQuarantinedButton.setForeground(new java.awt.Color(255, 255, 255));
        shredQuarantinedButton.setText("Shred Files");
        shredQuarantinedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shredQuarantinedButtonMouseClicked(evt);
            }
        });

        scanTimeButton.setBackground(new java.awt.Color(0, 102, 153));
        scanTimeButton.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        scanTimeButton.setForeground(new java.awt.Color(255, 255, 255));
        scanTimeButton.setText("Set Scan Time");
        scanTimeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scanTimeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout displaySettingsPanelLayout = new javax.swing.GroupLayout(displaySettingsPanel);
        displaySettingsPanel.setLayout(displaySettingsPanelLayout);
        displaySettingsPanelLayout.setHorizontalGroup(
                displaySettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(displaySettingsPanelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(displaySettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(shredQuarantinedLabel)
                                        .addGroup(displaySettingsPanelLayout.createSequentialGroup()
                                                .addGroup(displaySettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(scanTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(displaySettingsPanelLayout.createSequentialGroup()
                                                                .addComponent(scanTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(scanTimeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(137, 137, 137)
                                                .addGroup(displaySettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(clearReportsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(clearReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(shredQuarantinedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(scanTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(42, Short.MAX_VALUE))
        );
        displaySettingsPanelLayout.setVerticalGroup(
                displaySettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(displaySettingsPanelLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(scanTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(displaySettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(scanTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(scanTimeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(scanTimeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                                .addGroup(displaySettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(shredQuarantinedLabel)
                                        .addComponent(clearReportsLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(displaySettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(shredQuarantinedButton)
                                        .addComponent(clearReportsButton))
                                .addGap(101, 101, 101))
        );

        mainPanel.add(displaySettingsPanel, "settingsCard");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
                bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(scanTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        bgLayout.setVerticalGroup(
                bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                .addComponent(scanTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scanPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scanPanelMouseClicked
        changeMainPanelCard("scanCard");
    }//GEN-LAST:event_scanPanelMouseClicked

    private void reportsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsPanelMouseClicked
        changeMainPanelCard("reportsCard");
        // clear reports panel
        reportListPanel.removeAll();

        // TODO get the reports & populate panel
        File reports_dir = new File("reports/");
        if (!reports_dir.exists()) {
            reports_dir.mkdir();
        }
        for (String report_name : reports_dir.list()) {
            if (report_name == null) {
                continue;
            }
            JButton report_label = new JButton(report_name);
            report_label.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    reportsButtonMouseClicked(evt, report_name);
                }
            });
            reportListPanel.add(report_label);
        }
        VirusSniperGUI.manualRefresh();
    }//GEN-LAST:event_reportsPanelMouseClicked

    private void reportsButtonMouseClicked(java.awt.event.MouseEvent evt, String report_name) {
        File reportFile = new File("reports/" + report_name);
        VirusSniperPopUp pop = new VirusSniperPopUp(reportFile);
        pop.setAlwaysOnTop(true);
        pop.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pop.setVisible(true);
    }

    private void scanPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scanPanelMouseEntered
        JPanel parent = (JPanel) evt.getSource();
        parent.setBackground(new java.awt.Color(0, 0, 102));
    }//GEN-LAST:event_scanPanelMouseEntered

    private void scanPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scanPanelMouseExited
        JPanel parent = (JPanel) evt.getSource();
        parent.setBackground(new java.awt.Color(0, 102, 153));
    }//GEN-LAST:event_scanPanelMouseExited

    private void reportsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsPanelMouseEntered
        JPanel parent = (JPanel) evt.getSource();
        parent.setBackground(new java.awt.Color(0, 0, 102));
    }//GEN-LAST:event_reportsPanelMouseEntered

    private void reportsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsPanelMouseExited
        JPanel parent = (JPanel) evt.getSource();
        parent.setBackground(new java.awt.Color(0, 102, 153));
    }//GEN-LAST:event_reportsPanelMouseExited

    private void quarantinedFilesPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quarantinedFilesPanelMouseEntered
        JPanel parent = (JPanel) evt.getSource();
        parent.setBackground(new java.awt.Color(0, 0, 102));
    }//GEN-LAST:event_quarantinedFilesPanelMouseEntered

    private void quarantinedFilesPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quarantinedFilesPanelMouseExited
        JPanel parent = (JPanel) evt.getSource();
        parent.setBackground(new java.awt.Color(0, 102, 153));
    }//GEN-LAST:event_quarantinedFilesPanelMouseExited

    private void settingsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsPanelMouseEntered
        JPanel parent = (JPanel) evt.getSource();
        parent.setBackground(new java.awt.Color(0, 0, 102));
    }//GEN-LAST:event_settingsPanelMouseEntered

    private void settingsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsPanelMouseExited
        JPanel parent = (JPanel) evt.getSource();
        parent.setBackground(new java.awt.Color(0, 102, 153));
    }//GEN-LAST:event_settingsPanelMouseExited

    private void quarantinedFilesPanelMouseClicked(java.awt.event.MouseEvent evt) throws IOException, NoSuchAlgorithmException {//GEN-FIRST:event_quarantinedFilesPanelMouseClicked
        changeMainPanelCard("quarantinedCard");

        DefaultTableModel model = (DefaultTableModel) quarantinedTable.getModel();
        model.setRowCount(0);

        MessageDigest md5 = MessageDigest.getInstance("MD5");
        File quarantined_dir = new File("quarantine/");
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
        for (File file : quarantined_dir.listFiles()) {
            Object[] attributes = new Object[4];
            String file_name = file.getName();
            String checksum = getFileChecksum(md5, file);
            String quarantine_date = sdf.format(file.lastModified());
            attributes[0] = file_name;
            attributes[1] = quarantine_date;
            attributes[2] = checksum;
            attributes[3] = "Malware";
            model.addRow(attributes);
        }
    }//GEN-LAST:event_quarantinedFilesPanelMouseClicked

    @SuppressWarnings("empty-statement")
    private static String getFileChecksum(MessageDigest digest, File file) throws IOException {
        //Create byte array to read data in chunks
        try ( //Get file input stream for reading the file content
                FileInputStream stream = new FileInputStream(file)) {
            //Create byte array to read data in chunks
            byte[] hashArray = new byte[1024];
            int bytesCount = 0;
            //Read file data and update in message digest
            while ((bytesCount = stream.read(hashArray)) != -1) {
                digest.update(hashArray, 0, bytesCount);
            };
        }

        //Get the hash's bytes
        byte[] bytes = digest.digest();

        //Convert it to hexadecimal format
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < bytes.length; i++) {
            sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
        }

        return sb.toString();
    }

    private void settingsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsPanelMouseClicked
        changeMainPanelCard("settingsCard");
    }//GEN-LAST:event_settingsPanelMouseClicked

    private void fileScanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileScanButtonActionPerformed
        FileScan fs = new FileScan();
        fs.scanFile();
    }//GEN-LAST:event_fileScanButtonActionPerformed

    private void suspiciousActivityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suspiciousActivityButtonActionPerformed
        try {
            SuspiciousActivity sa = new SuspiciousActivity();
            if (sa.getPsexec() || sa.getNewUsers()) {
                Report r = new Report(Report.ReportType.SUSPICIOUSACTIVITY, sa.toString(), null);
                File reportFile = new File(r.file_name);
                VirusSniperPopUp pop = new VirusSniperPopUp(reportFile);
                pop.setAlwaysOnTop(true);
                pop.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                pop.setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(null, "No Suspicious Activity Found", "", JOptionPane.PLAIN_MESSAGE);
            }
        } catch (IOException ex) {
            Logger.getLogger(VirusSniperGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_suspiciousActivityButtonActionPerformed

    private void venomScanButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venomScanButtonMouseClicked
        MSFVenom msf = new MSFVenom();
    }//GEN-LAST:event_venomScanButtonMouseClicked

    private void registryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registryButtonMouseClicked
        //Registry reg = new Registry();
        RegistryFrame regFrame = new RegistryFrame();
        regFrame.setVisible(true);
    }//GEN-LAST:event_registryButtonMouseClicked

    private void clearReportsButtonMouseClicked(MouseEvent evt) {
        File quarantined_dir = new File("reports/");
        Integer count = 0;
        for (File file : quarantined_dir.listFiles()) {
            if (!file.delete()) {
                JOptionPane.showMessageDialog(null, "Failed to delete " + file.toString(), "", JOptionPane.PLAIN_MESSAGE);
            } else {
                count++;
            }
        }
        JOptionPane.showMessageDialog(null, count.toString() + " reports deleted.", "", JOptionPane.PLAIN_MESSAGE);
    }

    private void shredQuarantinedButtonMouseClicked(MouseEvent evt) {
        File quarantined_dir = new File("quarantine/");
        Integer count = 0;
        for (File file : quarantined_dir.listFiles()) {
            if (!file.delete()) {
                JOptionPane.showMessageDialog(null, "Failed to delete " + file.toString(), "", JOptionPane.PLAIN_MESSAGE);
            } else {
                count++;
            }
        }
        JOptionPane.showMessageDialog(null, count.toString() + " quarantined files deleted.", "", JOptionPane.PLAIN_MESSAGE);
    }

    private void scanTimeButtonMouseClicked(MouseEvent evt) {
        try {
            Integer st = Integer.parseInt(scanTimeTF.getText());
            String period = scanTimeCB.getSelectedItem().toString();
            switch (period) {
                case "Days":
                    Settings.setScanTime(st);
                    break;
                case "Months":
                    Settings.setScanTime(st * 31);
                    break;
                case "Years":
                    Settings.setScanTime(st * 365);
                    break;
            }
            JOptionPane.showMessageDialog(null, "Scan time changed to " + st.toString() + " " + period, "", JOptionPane.PLAIN_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: Scan time must be an integer.", "", JOptionPane.PLAIN_MESSAGE);
        }

    }

    public void changeMainPanelCard(String card) {
        CardLayout cl = (CardLayout) (mainPanel.getLayout());
        cl.show(mainPanel, card);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VirusSniperGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VirusSniperGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VirusSniperGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VirusSniperGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Check to make sure quarantined directory exists */
        File quarantined_dir = new File("quarantine/");
        if (!quarantined_dir.exists()) {
            quarantined_dir.mkdir();
            quarantined_dir.setReadable(true, false);
            quarantined_dir.setWritable(true, false);
            quarantined_dir.setExecutable(false, false);
        }

        /* Create and display the form */
        main_gui = new VirusSniperGUI();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                main_gui.setVisible(true);
            }
        });
    }

    public static void manualRefresh() {
        main_gui.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel displayQuarantinedPanel;
    private javax.swing.JPanel displayReportsPanel;
    private javax.swing.JPanel displayScansPanel;
    private javax.swing.JPanel displaySettingsPanel;
    private javax.swing.JButton fileScanButton;
    private javax.swing.JLabel reportsPanelLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel quarantineIcon;
    private javax.swing.JLabel quarantineLabel;
    private javax.swing.JPanel quarantinedFilesPanel;
    private javax.swing.JTable quarantinedTable;
    private javax.swing.JButton registryButton;
    private javax.swing.JLabel registryIcon;
    private javax.swing.JLabel reportIcon;
    private javax.swing.JLabel reportsLabel;
    private javax.swing.JPanel reportsPanel;
    private javax.swing.JLabel scanIcon;
    private javax.swing.JLabel scanLabel;
    private javax.swing.JPanel scanPanel;
    private javax.swing.JPanel scanTitlePanel;
    private javax.swing.JLabel settingsIcon;
    private javax.swing.JLabel settingsLabel;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JButton suspiciousActivityButton;
    private javax.swing.JLabel suspiciousIcon;
    private javax.swing.JLabel venomIcon;
    private javax.swing.JButton venomScanButton;
    private javax.swing.JLabel virusIcon;
    private javax.swing.JComboBox<String> scanTimeCB;
    private javax.swing.JButton clearReportsButton;
    private javax.swing.JLabel clearReportsLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel scanTimeLabel;
    private javax.swing.JTextField scanTimeTF;
    private javax.swing.JButton shredQuarantinedButton;
    private javax.swing.JLabel shredQuarantinedLabel;
    private javax.swing.JButton scanTimeButton;
    // End of variables declaration//GEN-END:variables
    private JPanel reportListPanel;
}
